services:
  app:
    image: stac-utils/stac-fastapi-pgstac
    restart: always
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
      - PGHOST=database
      - PGPORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
      - ENABLE_TRANSACTIONS_EXTENSIONS=TRUE
      - STAC_FASTAPI_TITLE=NDP STAC
      - STAC_FASTAPI_DESCRIPTION=NDP STAC Catalog
    volumes:
      - .:/app
    depends_on:
      - database
    command: bash -c "./scripts/wait-for-it.sh database:5432 && uvicorn stac_fastapi.pgstac.app:app --host 0.0.0.0 --port 8082 --proxy-headers --forwarded-allow-ips=* --root-path=/stac"
    networks:
      network:
        ipv4_address: 172.20.0.3
 
  database:
    image: ghcr.io/stac-utils/pgstac:v0.9.2
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    volumes:
      - /data/stac-postgres:/var/lib/postgresql/data
    command: postgres -N 500
    networks:
      network:
        ipv4_address: 172.20.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
